app01/urls.py
from django.conf.urls import url
from app01 import views
urlpatterns = [
    url(r'^del_article/$',views.del_article),
    url(r'^addArticle/$',views.addArticle),
    url(r'^cnblogs/$',views.cnblog),
    url(r'^cnblogs/(\d+)/$',views.edit_article),
    url(r'^(?P<username>.*)/(?P<leibie>tag|category|archive)/(?P<canshu>.*)/$', views.homeSite),
    url(r'^(?P<username>.*)/p/(?P<id>.*)/$', views.article),
    url(r'^(?P<username>.*)/$', views.homeSite),
]

my_newblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app01 import views
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', views.index),
    url(r'^$', views.index),
    url(r'^cate/(?P<cate>.*)/$', views.index),
    url(r'^reg/$', views.reg),

    url(r'^poll/$', views.poll),
    url(r'^del/$', views.dell),
    url(r'^test/(?P<article_id>\d+)$', views.test),

    url(r'^login/$', views.login),
    url(r'^img/', views.img),
    url(r'^article_img/', views.article_img),
    url(r'^logout/$', views.logout),
    url(r'^pc-geetest/ajax_validate',views.pcajax_validate, name='pcajax_validate'),
    url(r'^pc-geetest/register', views.pcgetcaptcha, name='pcgetcaptcha'),

    url(r'^blog/', include('app01.urls')),
    url(r'^comment/', views.comment),
    # media 配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

app01/models.py
from django.db import models
from django.conf import settings
from bs4 import BeautifulSoup
# Create your models here.


class Info(models.Model):
    email = models.EmailField(verbose_name="邮箱")
    nickname = models.CharField(max_length=32, verbose_name="昵称", unique=True)
    tel = models.IntegerField(verbose_name="电话", unique=True, null=True, blank=True)
    avatar = models.FileField(verbose_name="头像", upload_to="avatar", default="/avatar/default.png")
    user = models.OneToOneField(to="User")

    def __str__(self):
        return self.nickname


class User(models.Model):   #settings  ：AUTH_USER_MODEL ="项目名称.UserInfo"
    '''用户信息表'''
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name="用户名",max_length=32)
    password = models.CharField(verbose_name="密码",max_length=64)
    create_time = models.DateTimeField(verbose_name="创建时间",auto_now_add=True)

    class Meta:
        verbose_name_plural = "用户信息表"

    def __str__(self):
        return self.username


class Article(models.Model):
    '''
    文章表
    '''
    title = models.CharField(max_length=64,verbose_name="文章标题")
    summary = models.CharField(max_length=244, verbose_name="文章概要")
    create_time = models.DateTimeField(verbose_name="创建时间",auto_now_add=True)
    update_time = models.DateTimeField(verbose_name="修改时间",auto_now=True)
    poll_count = models.IntegerField(verbose_name="点赞数",default=0)
    comment_count = models.IntegerField(verbose_name="评论数",default=0)
    read_count = models.IntegerField(verbose_name="阅读数",default=0)

    user = models.ForeignKey(to="User",verbose_name="所属作者",null=True,blank=True)
    classify = models.ForeignKey(to="Classfication",verbose_name="所属类别",null=True,blank=True)
    tags = models.ManyToManyField(to="Tag",through="Article2tag",through_fields=('article', 'tag'),verbose_name="所属标签")
    webartilecla = models.ForeignKey(verbose_name="文章所述主页文章类",to="Web_artile_cla",null=True)

    class Meta:
        verbose_name_plural = "文章表"

    def __str__(self):
        return self.title


class Web_class(models.Model):
    """
    网站分类表
    """
    name = models.CharField(verbose_name="网站分类名",max_length=32)

    def __str__(self):
        return self.name


class Web_artile_cla(models.Model):
    """
    网站文章分类表
    """
    name = models.CharField(max_length=32)
    webclass = models.ForeignKey(verbose_name="网站文章分类名",to="Web_class")

    def __str__(self):
        return self.name


class Article_detail(models.Model):
    '''文章细节表'''
    article = models.OneToOneField(to="Article",verbose_name="所属文章")
    content =models.TextField(verbose_name="文章内容")

    class Meta:
        verbose_name_plural = "文章细节表"

    def __str__(self):
        return self.content


class Tag(models.Model):
    '''标签表'''
    name = models.CharField(max_length=32,verbose_name="标签名")
    blog = models.ForeignKey(to="Blog",verbose_name="所属博客")
    class Meta:
        verbose_name_plural = "标签表"

    def __str__(self):
        return self.name


class Article2tag(models.Model):
    article = models.ForeignKey(verbose_name="文章",to="Article")
    tag = models.ForeignKey(verbose_name="标签",to="Tag")
    class Meta:
        '''联合唯一'''
        unique_together = [
            ("article","tag")
        ]


class Comment(models.Model):
    '''评论表'''
    time = models.DateTimeField(verbose_name="评论时间",auto_now_add=True)
    content = models.CharField(max_length=265,verbose_name="评论内容")
    up_count = models.IntegerField(default=0)
    user = models.ForeignKey(to="User",verbose_name="评论人",null=True,blank=True)
    article = models.ForeignKey(to="Article",verbose_name="评论文章",null=True,blank=True)
    farther_comment = models.ForeignKey(to="Comment",verbose_name="父级评论",null=True,blank=True)
    # farther_comment = models.ForeignKey("self",verbose_name="父级评论",null=True,blank=True)

    class Meta:
        verbose_name_plural = "评论表"


class Article_poll(models.Model):
    '''文章点赞表'''
    time = models.DateTimeField(verbose_name="点赞时间",auto_now_add=True)
    article = models.ForeignKey(to="Article",verbose_name="点赞文章",null=True,blank=True)   #一个文章可以有多个赞
    user = models.ForeignKey(to="User",verbose_name="点赞人",null=True,blank=True)
    # is_positive = models.BooleanField(default=1,verbose_name="点赞或踩")

    class Meta:
        '''联合唯一'''
        unique_together = ("user", "article",)
        verbose_name_plural = "文章点赞表"


class Comment_poll(models.Model):
    '''评论点赞表'''
    time=models.DateTimeField(verbose_name="点赞时间",auto_now_add=True)
    # is_positive = models.BooleanField(verbose_name="点赞或踩",default=1)
    user = models.ForeignKey(to="User",verbose_name="点赞用户",null=True,blank=True)
    comment = models.ForeignKey(to="Comment",verbose_name="点赞所属评论",null=True,blank=True)   #一个评论可以有多个赞

    class Meta:
        '''联合唯一'''
        unique_together = ("user","comment",)
        verbose_name_plural = "评论点赞表"


class Blog(models.Model):
    '''个人站点表'''
    title = models.CharField(max_length=32,verbose_name="个人博客标题")
    url = models.CharField(max_length=64,verbose_name="路径",unique=True)
    theme = models.CharField(max_length=32,verbose_name="博客主题")
    user = models.OneToOneField(to="User", verbose_name="所属用户")
    class Meta:
        '''通过admin录入数据的时候个中文显示'''
        verbose_name_plural = "个人站点表"

    def __str__(self):
        return self.title


class Classfication(models.Model):
    '''博主个人文章分类表'''
    title = models.CharField(max_length=32, verbose_name="分类标题")
    blog = models.ForeignKey(to="Blog",verbose_name="所属博客")

    class Meta:
        verbose_name_plural = "分类表"

    def __str__(self):
        return self.title

templates/addArticle.html
{% extends 'cnblog.html' %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">添加新文章</div>
        <div class="panel-body">
            <form action="/blog/addArticle/" method="post" novalidate>
                {% csrf_token %}
                <p>标题:{{ form.title }}{{ form.errors.title.0 }}</p>
                <p>内容:{{ form.content }}</p>
                <p><input id="summary" type="text" style="display: none" name="summary" value=""></p>
                <p style="color: blue">标签：</p>
                <div style="width: 100%;height: 30px;background-color: #2aabd2">
                {% for tag in tag_list %}
                    <span style="margin-left: 20px"><input style="margin-top: 10px" type="checkbox" name="tag" value="{{ tag.id }}">&nbsp;&nbsp;{{ tag.name }}</span>
                {% endfor %}
                </div>
                <br>
                <br>

                <p style="color: fuchsia">分类：</p>
                <div style="width: 100%;height: 30px;background-color: lawngreen">
                {% for cla in class_list %}
                    <span style="margin-left: 20px"><input style="margin-top: 10px" type="radio" name="cla" value="{{ cla.id }}">&nbsp;&nbsp;{{ cla.title }}</span>
                {% endfor %}
                </div>
                <p><input id="sub" type="submit" style="background-color: #2aabd2;margin-top: 20px">{{ form.errors.content.0 }}</p>
            </form>
        </div>
    </div>


    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#id_content',{
                width:"100%",
                height:300,
                resizeType:0,
                uploadJson:"/article_img/",
                extraFileUploadParams:{
                    csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                }
            });
        });
        $("#sub").click(function () {
           $("#summary").val(editor.text())
        })

    </script>

{% endblock %}

templates/cnblog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <script src="/static/jquery3.2.1.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <script src="/static/kindeditor/kindeditor-all-min.js"></script>

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header" style="height: 80px">
            <a class="navbar-brand" href="#"><img src="/static/adminlogo.gif" alt=""></a>
        </div>
        <div style="margin-top: 5px" class="pull-right"><a href="/blog/{{  request.session.userinfo.name }}/"><h2>{{ request.session.userinfo.name }}</h2></a></div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">操作</div>
                <div class="panel-body">
                    <p><a href="/blog/addArticle/">添加新文章</a></p>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">分类</div>
                <div class="panel-body">
                    <a href="">[编辑分类]</a>
                </div>
            </div>
        </div>
        <div class="col-md-8">
        {% block content %}
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    <div class="bs-example" data-example-id="simple-table">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th class="col-md-8"><a href="">标题</a></th>
                                <th class="col-md-1">评论数</th>
                                <th class="col-md-1">阅读数</th>
                                <th class="col-md-1">操作</th>
                                <th class="col-md-1">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for article in article_set %}
                                <tr>
                                    <th scope="row"><a href="/blog/{{ request.session.userinfo.name }}/p/{{ article.id }}">{{ article.title }}({{ article.create_time|date:'Y-m-d h:i' }})</a></th>
                                    <td>{{ article.comment_count }}</td>
                                    <td>{{ article.read_count }}</td>
                                    <td><a href="/blog/cnblogs/{{ article.id }}/">编辑</a></td>
                                    <td><a article_id="{{ article.id }}" class="del">删除</a></td>
                                </tr>
                            {% endfor %}


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
         {% endblock %}
        </div>
    </div>
</div>

<script>
    $(function () {
        $('.del').click(function () {
            $(this).addClass("is_me");
           $.ajax({
               url:'/blog/del_article/',
               type:"GET",
               dataType:"json",
               data:{
                   article_id:$(this).attr("article_id")
               },
               success:function (data) {
                    if (data){
                       $(".is_me").parent().parent().html("<td style='color:red'>删除成功</td>")
                    }
               }
           })
        })
    })
</script>
</body>
</html>

templates/editArticle.html
{% extends 'cnblog.html' %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">添加新文章</div>
        <div class="panel-body">
            <form action="/blog/cnblogs/{{ nid }}/" method="post" novalidate>
                {% csrf_token %}
                <p>标题:{{ form.title }}{{ form.errors.title.0 }}</p>
                <p>内容:{{ form.content }}</p>
                <p><input id="summary" type="text" style="display: none" name="summary" value=""></p>
                <p><input id="sub" type="submit" style="background-color: #2aabd2;margin-top: 20px">{{ form.errors.content.0 }}</p>
            </form>
        </div>
    </div>


    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#id_content',{
                width:"100%",
                height:300,
                resizeType:0,
                uploadJson:"/article_img/",
                extraFileUploadParams:{
                    csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                }
            });
        });
         $("#sub").click(function () {
           $("#summary").val(editor.text())
        })
    </script>

{% endblock %}

templates/editok.html
{% extends 'cnblog.html' %}
{% block content %}
        <div class="panel panel-default">
                <div class="panel-heading"><h1>修改成功</h1></div>
                <div class="panel-body">
                    <a href="/blog/cnblogs/">立即查看</a>
                </div>
            </div>
{% endblock %}

templates/error.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Error_404_资源不存在</title>
	<style type="text/css">
	body{margin:8% auto 0;max-width: 550px; min-height: 200px;padding:10px;font-family: Verdana,Arial,Helvetica,sans-serif;font-size:14px;}p{color:#555;margin:10px 10px;}img {border:0px;}.d{color:#404040;}
	</style>
</head>
<body>
<p><b>404.</b> 抱歉! 您访问的资源不存在!</p>
<p class="d">请确认您输入的网址是否正确，如果问题持续存在，请发邮件至contact&#64;cnblogs.com与我们联系。</p>
<p><a href="/">返回网站首页</a></p>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <script src="/static/jquery3.2.1.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <script src="/static/kindeditor/kindeditor-all-min.js"></script>
    {% block style %}

    {% endblock %}
</head>
<body>
{#导航条#}
<nav class="navbar" style="background-color: aqua">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a style="color:white" class="navbar-brand" href="/blog/{{ username }}">Hello&nbsp;{{ username }}</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">博客园</a></li>
        <li><a href="/">首页</a></li>
        <li><a href="#">新随笔</a></li>
        <li><a href="#">联系</a></li>
        <li><a href="#">订阅</a></li>
        <li><a href="/blog/cnblogs/">管理</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3" style="background-color: whitesmoke">
            <div class="panel panel-info" style="margin-top: 20px">
                <div class="panel-heading">
                    <h3 class="panel-title">公告</h3>
                </div>
                <div class="panel-body">
                    <img src="{{ userobj.info.avatar.url }}" width="80" height="80" style="margin-left: 20px">
                <h4>昵称：{{ userobj.info.nickname }}</h4>
                <h4>园龄：{{ userobj.create_time|timesince }}</h4>
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">我的标签</h3>
                </div>
                {% for tag in tag_list %}
                <div class="panel-body">
                    <a href="/blog/{{ username }}/tag/{{ tag.2 }}">{{ tag.0 }}({{ tag.1 }})</a>
                    </div>
                {% endfor %}
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">随笔分类</h3>
                </div>
                    {% for classify in classify_list %}
                        <div class="panel-body">
                            <a href="/blog/{{ username }}/category/{{ classify.2 }}">{{ classify.0 }}({{ classify.1 }})</a>
                        </div>
                    {% endfor %}
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">随笔档案</h3>
                </div>
                {% for time in dates %}
                     <div class="panel-body">
                         <a href="/blog/{{ username }}/archive/{{ time.0 }}">{{ time.0 }}({{ time.1 }})</a>
                    </div>
                {% endfor %}


            </div>

        </div>

        {#文章区#}
    {% block article %}
            <div class="col-md-8" style="background-color: whitesmoke">
            {% for article in articlelist %}
                    <div style="margin-top: 25px"><h4><a href="/blog/{{ username }}/p/{{ article.id }}">{{ article.title }}</a></h4></div>
                    <hr>
                    <div>{{ article.summary|safe }}......<a href="/blog/{{ username }}/p/{{ article.id }}">阅读全文</a></div>
                <p></p>
                <span style="margin-left: 550px;color: #999">
                    posted &nbsp;@ &nbsp;{{ article.create_time|date:"Y-m-d" }}&nbsp;{{ username }}&nbsp;评论({{ article.comment_count }})
                    &nbsp;<a style="color: #999" href="/blog/cnblogs/{{ article.id }}/">编辑</a></span>
            {% endfor %}
        </div>
    {% endblock %}

    </div>
</div>
{% block ajax %}

{% endblock %}


</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>

    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <script src="/static/jquery3.2.1.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <style>
        .content {
            overflow: hidden;
            word-wrap: break-word;
            width: 400px;
            border-bottom: 1px #e3e3e3 solid;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header ">
            <span class="navbar-brand" style="margin-left: 50px">博客园</span>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav" style="margin-left: 100px">
                <li class="active"><a href="/">主页</a></li>
                <li><a href="#">随笔</a></li>
                <li><a href="#">园子</a></li>
                <li><a href="#">新闻</a></li>
                <li><a href="#">博问</a></li>
                <li><a href="#">小组</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.userinfo %}
                    <li><h4 style="color: white;margin-top: 15px;margin-right: 30px"><span
                            class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;&nbsp;
                        <a style="color: white"
                           href="/blog/{{ request.session.userinfo.name }}">{{ request.session.userinfo.name }}</a>
                    </h4></li>
                    <li style="margin-right: 100px"><a href="/logout/">注销</a></li>
                {% else %}
                    <li style="margin-right: 30px"><a href="/login/">登陆</a></li>
                    <li style="margin-right: 100px"><a href="/reg/">注册</a></li>
                {% endif %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <div class="row">
        {#        网站分类#}
        <div class="col-md-2" style="margin-left: 50px">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">网站分类</h3>
                </div>
                {% for web in web_obj %}
                    <div class="panel panel-default server" style="margin-top: 20px">
                        <div class="panel-heading">{{ web.name }}</div>
                        {% for artile_cls in web.web_artile_cla_set.all %}
                            <div class="panel-body hide">
                                <a href="/cate/{{ artile_cls.name }}">{{ artile_cls.name }}</a>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </div>

        {#    文章区#}
        <div class="col-md-7" style="margin-left: 50px">
            {% for art in artile %}
                <p><a href="/blog/{{ art.user.username }}/p/{{ art.id }}/">{{ art.title }}</a></p>
                <div class="content">
                    <div class="row">
                        <div class="col-md-2">
                            <a href="/blog/{{ art.user.username }}/">
                                <img src="{{ art.user.info.avatar.url }}" width="60px" height="60px"></a></div>
                        <div class="col-md-10">{{ art.summary|safe }}</div></div>
                    <div class="row">
                        <div class="col-md-12">
                            <p style="margin-top: 20px"><a href="/blog/{{ art.user.username }}">{{ art.user.username }}</a>
                                发表于{{ art.create_time|date:"Y-m-d" }}
                            <a style="margin-left: 15px" href=""><span class="glyphicon glyphicon-comment"
                                                                   aria-hidden="true"></span>&nbsp;comment({{ art.comment_count }}) </a>
                            <a style="margin-left: 15px" href=""><span class="glyphicon glyphicon-thumbs-up"
                                                                   aria-hidden="true"></span>&nbsp;up({{ art.poll_count }})</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        <div class="row">
            <div class="col-md-12">
                <nav aria-label="Page navigation" style="margin-left: 60px">
                <ul class="pagination">
                    <li>
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li>
                        <a href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
            </div>
        </div>
        </div>




        <div class="col-md-3"></div>
    </div>
</div>


<script>
    $(function () {
        $(".server").mouseenter(function () {
            $(this).children().first().siblings().removeClass("hide")
        })
    });
    $(function () {
        $(".server").mouseleave(function () {
            $(this).children().first().siblings().addClass("hide")
        })
    })
</script>
</body>
</html>

templates/ok.html
{% extends 'cnblog.html' %}

{% block content %}
        <div class="panel panel-default">
                <div class="panel-heading"><h1>ok</h1></div>
                <div class="panel-body">
                    <a href="/blog/cnblogs/">立即查看</a>
                </div>
            </div>
{% endblock %}

templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <style>
         .file,.avatar{
            width: 40px;
            height: 40px;
            position: absolute;
            left: 80px;
            bottom: -10px;
        }
        .ava{
            position: relative;
        }
        .file{
        opacity: 0;
        }
        body{
            background-image: url("/static/homescreen.jpeg");
        }
        .sty{
            margin-top: 100px;
            margin-left: 500px;
        }
    </style>
</head>
<body>
<div class="sty">
<form>
    {% csrf_token %}

<p>{{ form.email.label }}{{ form.label_suffix }}{{ form.email }} <span></span></p>
<p>{{ form.tel.label }}{{ form.label_suffix }}{{ form.tel }}<span></span></p>
<p>{{ form.username.label }}{{ form.label_suffix }}{{ form.username }}<span></span></p>
<p>{{ form.nickname.label }}{{ form.label_suffix }}{{ form.nickname }}<span></span></p>
<p>{{ form.password.label }}{{ form.label_suffix }}{{ form.password }}<span></span></p>
<p>{{ form.confirmPassword.label }}{{ form.label_suffix }}{{ form.confirmPassword }}<span></span></p>
    <p class="ava">头像：<img class="avatar" src="/static/default.png"><input class="file" type="file" name="avatar"></p>
    </form>
<p><button>注册</button></p>
</div>
<script src="/static/jquery3.2.1.js"></script>
<script src="/static/jquery.cookie.js"></script>
<script>
    $(".file").change(function () {
        var file=$(this)[0].files[0]; //获取改变之后的文件
        var reader=new FileReader();  //实例化一个文件读取者
        reader.readAsDataURL(file);    //读取文件的过程，获得路径
        reader.onload=function () {   // 文件路径加载完之后的操作 the result就是文件的路径
            $(".avatar")[0].src=this.result
        }
    });

    $(function () {
        $("button").click(function () {
           var formdata = new FormData();
           formdata.append("username",$("#id_username").val());
           formdata.append("password",$("#id_password").val());
           formdata.append("confirmPassword",$("#id_confirmPassword").val());
           formdata.append("email",$("#id_email").val());
           formdata.append("tel",$("#id_tel").val());
           formdata.append("nickname",$("#id_nickname").val());
           formdata.append("avatar",$(".file")[0].files[0]);
           formdata.append("csrfmiddlewaretoken",$("[name='csrfmiddlewaretoken']").val());
            $.ajax({
                url:"/reg/",
                type:"POST",
{#                headers:{"X-CSRFToken":$.cookie('csrftoken')},#}
                data:formdata,
                contentType:false,
                processData:false,
                success:function (data) {

                    if (!JSON.parse(data)){
                        window.location.href="/login/"
                    }
                    for (var i in JSON.parse(data)){
                       $("#id_"+i).next().html(JSON.parse(data)[i][0]);
{#                       $('[name='+i+']').next().html(JSON.parse(data)[i][0]);#}
                    }
                    if (!("email" in JSON.parse(data))){
                        $("[name='email']").next().html("")
                    }if (!("tel" in JSON.parse(data))){
                        $("[name='tel']").next().html("")
                    }if (!("username" in JSON.parse(data))){
                        $("[name='username']").next().html("")
                    }if (!("nickname" in JSON.parse(data))){
                        $("[name='nickname']").next().html("")
                    }if (!("password" in JSON.parse(data))){
                        $("[name='password']").next().html("")
                    }if (!("confirmPassword" in JSON.parse(data))){
                        $("[name='confirmPassword']").next().html("")
                    }
                }
            })
        })
    })
</script>
</body>
</html>